config/routes.rb
Rails.application.routes.draw do

  resources :newsletters
  resources :contacts
  get "downloader", to: 'newsletters#download'

  root to: 'frontend#index'
  get 'gallery/:category_permalink', to: 'frontend#gallery', as: "gallery"
  get 'index/:category_permalink', to: 'frontend#index', as: "conferencia"

  get 'cursos', to: 'payments#categories', as: 'courses_front'
  get 'cursos/:id', to: 'payments#courses_categories', as: 'app_courses'
  get 'promotionbook', to: 'frontend#book', as: 'promotion_book'

  get '/mercadopago/:id', to: 'payments#front_mercadopago', as: "front_mercadopago"
  get 'payments/:id/:method', to:'payments#checkout_mercadopago', as:"payment_mercadopago"

  get 'paypal/:id', to: 'payments#front_paypal', as: 'front_paypal'
  post '/', to: 'payments#transaction_paypal', as: "checkout_paypal"
  get 'payments/:id/paypal/:id', to:'payments#checkout_paypal', as:"payment_paypal"

  post '/checkout', to: 'payments#checkout', as: "checkout"
  get '/checkout/:id', to: 'payments#checkout_id', as: "checkout_id"

  # post '/', to: 'payments#create', as: "app_create_subscriber"

  #
  # # get 'payments/:id/:method', to:'payments#payments', as:"payments"
  #
  #

  # #

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :bookshops do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

  end

  scope :admin do
    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
        resources :courses do
          get '(page/:page)', action: :index, on: :collection, as: ''
          get '/clone', action: 'clone'
          delete(
            action: :destroy_multiple,
            on: :collection,
            as: :destroy_multiple
          )
            resources :subscribers do
              get '(page/:page)', action: :index, on: :collection, as: ''
              get '/clone', action: 'clone'
              delete(
                action: :destroy_multiple,
                on: :collection,
                as: :destroy_multiple
              )
            end
        end
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  post '/send_mailer', to: 'frontend#send_mailer'

  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'


end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	validates_uniqueness_of :email
	validates_presence_of :email
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, message: "No es un email valido" }
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  # GET /newsletters
  # GET /newsletters.json
  def index
    #@newsletters = Newsletter.all
  end
  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  def download
    @filename ="#{Rails.root}/app/assets/images/frontend/Llamados_para_triunfar_GUSTAVO_HENAO.mp3"
    send_file(@filename,
      :type => 'audio/mp3',
      :disposition => 'attachment',
      :x_sendfile => true)
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        @@gibbon.lists("86f169fb8e").members.create(body:{email_address: @newsletter.email, status: "subscribed"})   
        format.html { redirect_to downloader_path, notice: 'Se ha suscrito correctamente'}
      else
        format.html { redirect_to gallery_path("audios"), notice: 'Ya te encuentras registrado o ocurrio un error' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.haml
= simple_form_for @newsletter do |f|
	.row
		= f.input :email, type:'email'

		.form-actions.right
			= f.button :submit, "Guardar", class: "btn"

app/views/newsletters/edit.html.haml
= title "Newsletters - editar | #{@newsletter.id}"
= render 'form'

app/views/newsletters/index.html.haml
= title("Newsletters - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_newsletter_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |newsletter|
				= render 'listing', newsletter: newsletter
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado newsletters.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_newsletter_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/newsletters/new.html.haml
= title "Newsletters - Nuevo"
= render 'form'

app/views/newsletters/show.html.haml
= title "Newsletters | #{@newsletter.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Newsletter
				= link_to newsletter_path(@newsletter), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Newsletter
				= link_to edit_newsletter_path(@newsletter), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to newsletters_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @newsletter.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @newsletter.email.to_s.humanize