config/routes.rb
Rails.application.routes.draw do

  resources :newsletters
  resources :contacts
  get "downloader", to: 'newsletters#download'

  root to: 'frontend#index'
  get 'gallery/:category_permalink', to: 'frontend#gallery', as: "gallery"
  get 'index/:category_permalink', to: 'frontend#index', as: "conferencia"

  get 'cursos', to: 'payments#categories', as: 'courses_front'
  get 'cursos/:id', to: 'payments#courses_categories', as: 'app_courses'
  get 'promotionbook', to: 'frontend#book', as: 'promotion_book'

  get '/mercadopago/:id', to: 'payments#front_mercadopago', as: "front_mercadopago"
  get 'payments/:id/:method', to:'payments#checkout_mercadopago', as:"payment_mercadopago"

  get 'paypal/:id', to: 'payments#front_paypal', as: 'front_paypal'
  post '/', to: 'payments#transaction_paypal', as: "checkout_paypal"
  get 'payments/:id/paypal/:id', to:'payments#checkout_paypal', as:"payment_paypal"

  post '/checkout', to: 'payments#checkout', as: "checkout"
  get '/checkout/:id', to: 'payments#checkout_id', as: "checkout_id"

  # post '/', to: 'payments#create', as: "app_create_subscriber"

  #
  # # get 'payments/:id/:method', to:'payments#payments', as:"payments"
  #
  #

  # #

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :bookshops do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

  end

  scope :admin do
    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
        resources :courses do
          get '(page/:page)', action: :index, on: :collection, as: ''
          get '/clone', action: 'clone'
          delete(
            action: :destroy_multiple,
            on: :collection,
            as: :destroy_multiple
          )
            resources :subscribers do
              get '(page/:page)', action: :index, on: :collection, as: ''
              get '/clone', action: 'clone'
              delete(
                action: :destroy_multiple,
                on: :collection,
                as: :destroy_multiple
              )
            end
        end
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  post '/send_mailer', to: 'frontend#send_mailer'

  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'


end

app/models/subscriber.rb
#Generado por keppler
require 'elasticsearch/model'
class Subscriber < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :course, counter_cache: true
  validates :bill, uniqueness: true
  require 'mercadopago.rb'

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end


  def self.buy_mercadopago(params)
    $mp = MercadoPago.new('7540776543610704', 'hya2kL3DVD1NnQMTs4LgLa3KLOn1c4PT')

    preference_data = {
      :items => [
          {
          :id => "#{Course.find(params[:id]).subscribers_count}",
          :title => "#{Course.find(params[:id]).course_name}",
          :quantity => 1,
          :unit_price => Course.find(params[:id]).price_bs,
          :currency_id => "VEF"
          }
        ],
      :back_urls => {
        :success => "http://portal.gustavohenao.com/payments/#{params[:id]}/mercadopago",
        :failure => "http://portal.gustavohenao.com/checkout/Braintree_errors"
      },
      :auto_return => "approved",
      :payment_methods => {
          # :excluded_payment_methods => [
          #   {
          #   :id => "amex"
          #   }
          # ],
          :excluded_payment_types => [
              {
              :id => "ticket"
              },
              {
              :id => "bank_transfer"
              },
              {
              :id => "discount"
              }
            ],
          },
          # :notification_url => "localhost:3000/checkout/asd99",
      }

    @preference = $mp.create_preference(preference_data)
  end

  def self.paypal_payment(order_params)
    values = {
        business: "gagg1707_vendedor_seller@gmail.com",
        cmd: "_xclick",
        upload: 1,
        invoice: order_params[:name],
        return: "http:/localhost:3000/payments/#{order_params[:course_id]}/paypal/#{order_params[:name]}",
        amount: Course.find(order_params[:course_id]).price_dolars,
        item_name: "#{Course.find(order_params[:course_id]).course_name}",
        item_number: Course.find(order_params[:course_id]).id,
        quantity: '1',
        notify_url: "http:/localhost:3000"
    }
  end

  def self.amount(subscriber_params, course)

    if subscriber_params[:payment].eql?("mercadopago")
      amount = "#{course.price_bs}"
    else
      amount = "#{course.price_dolars}"
    end

  end

  def self.searching_checkout(checkout)
    Subscriber.all.where(bill: "#{checkout}").first
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      lastname:  self.lastname.to_s,
      document_id: self.document_id.to_s,
      email:  self.email.to_s,
      phone_one:  self.phone_one.to_s,
      phone_two:  self.phone_two.to_s,
      address:  self.address.to_s,
      course_id:  self.course_id.to_s,
      payment: self.payment.to_s,
      buyout: self.buyout.to_s,
      bill: self.bill.to_s,
    }.as_json
  end

end
#Subscriber.import

app/controllers/subscribers_controller.rb
#Generado con Keppler.
class SubscribersController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_course
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  def index
    subscribers = Subscriber.searching(@query).where(course_id: @course_subscriber.id)
    @objects, @total = subscribers.page(@current_page), subscribers.size
    redirect_to subscribers_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /subscribers/1
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new(course_id: params[:course_id])
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      redirect_to @subscriber.paypal_url(registration_path(@subscriber))
    else
      render :new
    end
  end

  # PATCH/PUT /subscribers/1
  def update
    if @subscriber.update(subscriber_params)
      redirect_to category_course_subscribers_path, notice: 'Subscriber was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subscribers/1
  def destroy
    @subscriber.destroy
    redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.'
  end

  def destroy_multiple
    Subscriber.destroy redefine_ids(params[:multiple_ids])
    redirect_to category_course_subscribers_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    def set_course
      @course_subscriber = Course.find(params[:course_id])
    end

    # Only allow a trusted parameter "white list" through.
    def subscriber_params
      params.require(:subscriber).permit(:name, :lastname, :email, :phone_one, :phone_two, :address, :category_id)
    end
end

app/views/subscribers/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/subscribers/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
		.wrapper-inputs
			.card
				=# simple_form_for @subscriber, :url => category_course_subscriber_path, :method => 'post' do |f|
				= simple_form_for @subscriber, :url => url_for(:action => 'create', :controller => 'subscribers'), :method => 'post' do |f|
					.row
						= f.input :name
						= f.input :lastname
						= f.input :email
						= f.input :phone_one
						= f.input :phone_two
						= f.input :bill
						= f.input :buyout
						= f.input :payment
						= f.input :address, input_html: {class: "materialize-textarea"}
						= f.hidden_field :course_id

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/subscribers/_index_show.html.haml
.listing-show-header
	.actions
		-# - if can? :update, Subscriber
		-# 	= link_to edit_subscriber_path(@subscriber), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
		-# 		= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @subscriber.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @subscriber.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.lastname")
			.display-value= @subscriber.lastname
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @subscriber.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.phone_one")
			.display-value= @subscriber.phone_one
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.phone_two")
			.display-value= @subscriber.phone_two
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.address")
			.display-value= @subscriber.address
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.course_id")
			.display-value= @subscriber.course_id


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/subscribers/_listing.html.haml
%tr{ id: "row-#{subscriber.id}" }
	- if can? :destroy_multiple, Subscriber
		%td.item-check{style:"width: 10%"}
			=# link_to "", subscriber_path(subscriber), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{subscriber.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{subscriber.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{subscriber.id}" }

		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(4,6), remote: true, class: "show-row"
			%span
				= subscriber.name
		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(params[:course_id], search: @query), remote: true, class: "show-row"
			%span
				= subscriber.lastname
		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(params[:course_id], search: @query), remote: true, class: "show-row"
			%span
				= subscriber.email
		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(params[:course_id], search: @query), remote: true, class: "show-row"
			%span
				= subscriber.phone_one
		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(params[:course_id], search: @query), remote: true, class: "show-row"
			%span
				= subscriber.phone_two
		%td{style:"width: 30%"}
			=# link_to "", category_course_subscriber_path(params[:course_id], search: @query), remote: true, class: "show-row"
			%span
				= subscriber.course_id


		%td{style:"width: 5%"}
			= link_to category_course_subscriber_path(params[:category_id],params[:course_id],subscriber.id), class: "btn-floating waves-effect btn-flat" do
				= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/subscribers/edit.html.haml
= title "Subscribers - editar | #{@subscriber.id}"
= render 'form'

app/views/subscribers/index.html.haml
= title("Subscribers - Listado")
.listing.col.l9.m12.s12
	-# if can? :new, model
	= link_to category_courses_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
		= material_icon.arrow_back
	= entries(@total, @objects)

	%table.bordered
		%tbody
			- @objects.each do |subscriber|
				= render 'listing', subscriber: subscriber
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado subscribers.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_category_course_subscriber_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")



:scss
	.separator{
		margin: 40px 30px 8px 30px;
	}

app/views/subscribers/new.html.haml
= title "Subscribers - Nuevo"
= render 'form'

app/views/subscribers/show.html.haml
= title "Subscribers | #{@subscriber.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Subscriber
				= link_to category_course_subscriber_path(params[:category_id],params[:course_id],@subscriber.id), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Subscriber
				= link_to edit_category_course_subscriber_path(params[:category_id],params[:course_id],@subscriber.id), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to category_course_subscribers_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @subscriber.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @subscriber.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.lastname")
					.display-value.fs-body-1.tc-black-2= @subscriber.lastname.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @subscriber.email.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.phone_one")
					.display-value.fs-body-1.tc-black-2= @subscriber.phone_one.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.phone_two")
					.display-value.fs-body-1.tc-black-2= @subscriber.phone_two.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.address")
					.display-value.fs-body-1.tc-black-2= @subscriber.address.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.course_id")
					.display-value.fs-body-1.tc-black-2= @subscriber.course_id.to_s.humanize

app/views/subscribers/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@subscriber.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");