config/routes.rb
Rails.application.routes.draw do

  resources :newsletters
  resources :contacts
  get "downloader", to: 'newsletters#download'

  root to: 'frontend#index'
  get 'gallery/:category_permalink', to: 'frontend#gallery', as: "gallery"
  get 'index/:category_permalink', to: 'frontend#index', as: "conferencia"

  get 'cursos', to: 'payments#categories', as: 'courses_front'
  get 'cursos/:id', to: 'payments#courses_categories', as: 'app_courses'
  get 'promotionbook', to: 'frontend#book', as: 'promotion_book'

  get '/mercadopago/:id', to: 'payments#front_mercadopago', as: "front_mercadopago"
  get 'payments/:id/:method', to:'payments#checkout_mercadopago', as:"payment_mercadopago"

  get 'paypal/:id', to: 'payments#front_paypal', as: 'front_paypal'
  post '/', to: 'payments#transaction_paypal', as: "checkout_paypal"
  get 'payments/:id/paypal/:id', to:'payments#checkout_paypal', as:"payment_paypal"

  post '/checkout', to: 'payments#checkout', as: "checkout"
  get '/checkout/:id', to: 'payments#checkout_id', as: "checkout_id"

  # post '/', to: 'payments#create', as: "app_create_subscriber"

  #
  # # get 'payments/:id/:method', to:'payments#payments', as:"payments"
  #
  #

  # #

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :bookshops do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

  end

  scope :admin do
    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
        resources :courses do
          get '(page/:page)', action: :index, on: :collection, as: ''
          get '/clone', action: 'clone'
          delete(
            action: :destroy_multiple,
            on: :collection,
            as: :destroy_multiple
          )
            resources :subscribers do
              get '(page/:page)', action: :index, on: :collection, as: ''
              get '/clone', action: 'clone'
              delete(
                action: :destroy_multiple,
                on: :collection,
                as: :destroy_multiple
              )
            end
        end
    end
  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  post '/send_mailer', to: 'frontend#send_mailer'

  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'


end

app/models/category.rb
#Generado por keppler
require 'elasticsearch/model'
class Category < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :courses, :dependent => :delete_all
  validates :name, presence: {message: "El campo no puede estar vacío"}

  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
    }.as_json
  end

end
#Category.import

app/controllers/categories_controller.rb
#Generado con Keppler.
class CategoriesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    categories = Category.searching(@query).all
    @objects, @total = categories.page(@current_page), categories.size
    redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def destroy_multiple
    Category.destroy redefine_ids(params[:multiple_ids])
    redirect_to categories_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/categories/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @category do |f|
					.row
						= f.input :name

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/categories/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Category
			= link_to edit_category_path(@category), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @category.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @category.name
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/categories/_listing.html.haml
%tr{ id: "row-#{category.id}" }
	- if can? :destroy_multiple, Category
		%td.item-check{style:"width: 10%"}
			= link_to "", category_path(category), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{category.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{category.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{category.id}" }

		%td{style:"width: 30%"}
			= link_to "", category_path(category, search: @query), remote: true, class: "show-row"
			%center
				= category.name

	%td{style:"width: 5%"}
		= link_to category_courses_path(category), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.school.css_class("md-dark")

	%td{style:"width: 5%"}
		= link_to category_path(category), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/categories/edit.html.haml
= title "Categories - editar | #{@category.id}"
= render 'form'

app/views/categories/index.html.haml
= title("Categories - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_category_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- unless @objects.blank?
				%tr{style:"background: #fff;"}
					%th
					%th.center Nombre
					%th
					%th{ colspan: 2}
			- @objects.each do |category|
				= render 'listing', category: category
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado categories.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_category_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/categories/new.html.haml
= title "Categories - Nuevo"
= render 'form'

app/views/categories/show.html.haml
= title "Categories | #{@category.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Category
				= link_to category_path(@category), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Category
				= link_to edit_category_path(@category), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @category.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @category.name.to_s.humanize

app/views/categories/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@category.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");